DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS secretStuff;
DROP TABLE IF EXISTS volunteerOpp;
DROP TABLE IF EXISTS attendence;

BEGIN;

CREATE TABLE users(
 id SERIAL PRIMARY KEY,
 username VARCHAR NOT NULL UNIQUE,
 password VARCHAR NOT NULL UNIQUE
);

CREATE TABLE secretstuff(
 secret_id SERIAL PRIMARY KEY,
 mySecret VARCHAR NOT NULL,
 myOtherSecret VARCHAR NOT NULL
);

CREATE TABLE volunteerOpp(
  id SERIAL PRIMARY KEY,
  cause VARCHAR(30) NOT NULL,
  title VARCHAR(64) NOT NULL,
  description text NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT NOW(),
  opp_date DATE,
  location VARCHAR(64),
  creator TEXT REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
  );

CREATE TABLE attendence(
  user_id INTEGER NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  opp INTEGER NOT NULL REFERENCES volunteerOpp(id) ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY(user_id, opp));

COMMIT;
